---
# tasks file for lighthouse-role
- name: NGINX | Install release
  become: true
  ansible.builtin.yum:
    name: epel-release
    state: present
- name: NGINX | Install NGINX
  become: true
  ansible.builtin.yum:
    name: nginx
    state: present
  notify: start nginx
- name: NGINX | Create general config
  become: true
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644
  # notify: reload-nginx
  notify: restart nginx  

# Check git
- name: lighthouse | install dependencies
  become: true
  ansible.builtin.yum:
    name: git
    state: present
- name: lighthouse | copy from git
  git:
    repo: "{{ lighthouse_vsc }}"
    version: master
    dest: "{{ lighthouse_location_dir }}"
    
- name: lighthouse | create lighthouse config
  become: true
  template:
    src: lighthouse.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: 0644
  notify: restart nginx